name: Laravel

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        composer install
        mkdir vendor/orchestra/testbench-core/laravel/app/Http
        mkdir vendor/orchestra/testbench-core/laravel/app/Http/Livewire
    - name: Create Database
      run: |
        ls vendor
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
        APP_ENV: testing
      run: ./vendor/bin/phpunit
